steps:
  # Build docker image with docker builder
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['build', '-t', 'gcr.io/$PROJECT_ID/sql-microservice-image:latest', '.']
  # Publish image to container registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sql-microservice-image:latest']
  # Execute kubectl command to update associated deployment image
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      [
        'set',
        'image',
        'deployment/sql-microservice-deployment',
        'backend=gcr.io/$PROJECT_ID/sql-microservice-image:latest',
      ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=training'
